[tool.poetry]
name = "webhook-utils"
version = "0.3.1"
description = "Short, well documented utilities for interacting with webhooks."
authors = ["Elijah Wilson <dev.tizz98@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tizz98/webhook-utils"
keywords = ["webhook", "utils", "utilities", "webhooks"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = {version = "^0.21.1", optional = true}
fastapi = {version = "^0.70.1", optional = true}
requests = {version = "^2.26.0", optional = true}

[tool.poetry.extras]
httpx = ["httpx"]
fastapi = ["fastapi", "requests"]

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"
pytest = "^6.2.5"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"
pytest-spec = "^3.2.0"
pytest-xdist = {extras = ["psutil"], version = "^2.5.0"}
tox-gh-actions = "^2.8.1"
respx = "^0.19.0"
flake8-print = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = 'black'

[tool.black]
target-version = ['py38']
